version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sbc_user
      - POSTGRES_PASSWORD=dRpa4yXJ3SDTjXk
      - POSTGRES_DB=sbc_erp_dev
volumes:
  postgres_data: